[colors.bright]
black = "#555753"
blue = "#739fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#000000"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#010e17"
foreground = "#cfcfcf"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono Light"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 4
y = 4
